import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import React from "react";
import Link from "next/link";
import TeamModal from "../components/TeamModal";
import { Trophy, Mail, Star, BookOpen, Users, Award, MessageSquare } from "lucide-react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="id">
      <body className="min-h-screen bg-gradient-to-br from-red-600 via-white to-red-100 relative">
        {/* Navigation Header */}
        <header className="bg-white shadow-lg border-b-4 border-red-600">
          <div className="container mx-auto px-4 py-4">
            <div className="flex items-center justify-between">
              <div className="flex items-center space-x-3">
                <Link href="/">
                  <div className="p-2 rounded-lg">
                    <img src="/logo-quiz.png" alt="Logo Quiz" className="h-8 w-8 object-contain" />
                  </div>
                </Link>
                <div>
                  <h1 className="text-2xl font-bold text-red-800">Quiz Kemerdekaan</h1>
                  <p className="text-sm text-red-600">Indonesian Independence Quiz</p>
                </div>
              </div>
              <nav className="hidden md:flex items-center space-x-6">
                <a href="/" className="flex items-center space-x-2 px-4 py-2 rounded-lg transition-colors text-red-600 hover:bg-red-50">
                  <BookOpen className="h-4 w-4" />
                  <span>Quiz</span>
                </a>
                <a href="/leaderboard" className="flex items-center space-x-2 px-4 py-2 rounded-lg transition-colors text-red-600 hover:bg-red-50">
                  <Trophy className="h-4 w-4" />
                  <span>Leaderboard</span>
                </a>
                <a href="/chat" className="flex items-center space-x-2 px-4 py-2 rounded-lg transition-colors text-red-600 hover:bg-red-50">
                  <MessageSquare className="h-4 w-4" />
                  <span>Chat AI</span>
                </a>
              </nav>
            </div>
          </div>
        </header>

        {/* Main Content */}
        <main className="container mx-auto px-4 py-8">
          {children}
        </main>

        {/* Footer */}
        <footer className="bg-red-800 text-white py-8 mt-16">
          <div className="container mx-auto px-4">
            <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
              <div>
                <div className="flex flex-col items-start mb-4">
                  <Link href="/">
                    <img src="/logo-quiz.png" alt="Logo Quiz" className="bg-white rounded-xl h-20 w-20 p-3 object-contain shadow-lg mb-3" />
                  </Link>
                  <span className="font-bold text-lg">Quiz Kemerdekaan</span>
                  <p className="text-sm text-red-100 mt-1">Indonesian Independence Quiz</p>
                </div>
                <p className="text-red-100">
                  Pelajari sejarah kemerdekaan Indonesia dengan cara yang menyenangkan dan interaktif melalui AI quiz yang edukatif.
                </p>
              </div>
              <div>
                <h3 className="font-semibold text-lg mb-4">Fitur Unggulan</h3>
                <ul className="space-y-2 text-red-100">
                  <li className="flex items-center space-x-2">
                    <Star className="h-4 w-4" />
                    <span>AI-Powered</span>
                  </li>
                  <li className="flex items-center space-x-2">
                    <Award className="h-4 w-4" />
                    <span>Digital Badges</span>
                  </li>
                  <li className="flex items-center space-x-2">
                    <Mail className="h-4 w-4" />
                    <span>Email Results</span>
                  </li>
                  <li className="flex items-center space-x-2">
                    <Users className="h-4 w-4" />
                    <span>Leaderboard</span>
                  </li>
                </ul>
              </div>
              <div>
                <h3 className="font-semibold text-lg mb-4">Tentang</h3>
                <p className="text-red-100 mb-4">
                  Dibuat untuk memperingati Hari Kemerdekaan Indonesia dengan teknologi AI modern untuk pembelajaran yang lebih engaging.
                </p>
                <div className="text-sm text-red-200">
                  Powered by <span className="inline-block align-middle"><TeamModal /></span> <span className="align-middle">• Built with ❤️ for Indonesia</span>
                </div>
              </div>
            </div>
            <div className="border-t border-red-700 mt-8 pt-6 text-center text-red-200">
              <p>&copy; 2025 Quiz Kemerdekaan. Merdeka! </p>
            </div>
          </div>
        </footer>
      </body>
    </html>
  );
}
